export const emojiDict: { [key: string]: string } = {
  // Animals
  monkey: "🐵",
  ape: "🐵",
  chimp: "🐵",
  dog: "🐶",
  puppy: "🐶",
  doggy: "🐶",
  cat: "🐱",
  kitty: "🐱",
  kitten: "🐱",

  // Food & Drink
  pizza: "🍕",
  coffee: "☕",
  cafe: "☕",
  wine: "🍷",
  beer: "🍺",
  drink: "🍸",
  cocktail: "🍹",
  champagne: "🍾",
  food: "🍽️",
  eat: "🍽️",
  hungry: "🍽️",
  chocolate: "🍫",
  strawberry: "🍓",
  banana: "🍌",
  peach: "🍑",
  eggplant: "🍆",
  lollipop: "🍭",

  // Emotions
  happy: "😊",
  joy: "😊",
  glad: "😊",
  cheerful: "😊",
  sad: "😢",
  cry: "😢",
  crying: "😢",
  upset: "😢",
  depressed: "😢",
  angry: "😠",
  mad: "😠",
  furious: "😠",
  rage: "😠",
  laugh: "😂",
  laughing: "😂",
  funny: "😂",
  hilarious: "😂",
  cool: "😎",
  awesome: "😎",
  amazing: "😎",
  love: "❤️",
  heart: "💖",
  loving: "❤️",
  adore: "❤️",
  crush: "😍",
  blush: "😊",
  kiss: "😘",
  kisses: "💋",
  hugging: "🤗",
  flirty: "😉",
  shy: "☺️",

  // Relationship & Romance
  date: "❤️",
  dating: "💘",
  couple: "👫",
  lovers: "💕",
  relationship: "💑",
  sex: "🍑🍆",
  sexy: "🔥",
  hot: "🥵",
  cuddle: "🤗",
  naked: "🙈",
  nude: "🙈",
  wink: "😉",
  kissme: "😘",
  hookup: "🍑",
  lips: "💋",
  bed: "🛏️",
  nightstand: "🌃",
  sleepover: "🛌",
  undercovers: "🔞",

  // Suggestive / Double-meaning
  "big deck": "🍌",
  dick: "🍆",
  ass: "🍑",
  splash: "💦",
  sweat: "💦",
  waterdrops: "💦",
  tongue: "👅",
  handcuffs: "🪢",
  blindfold: "🎭",
  whip: "🦯", // Closest general-purpose symbol
  bdsm: "🖤",
  flirt: "😏",
  tease: "😈",
  naughty: "😈",
  devil: "😈",
  angel: "😇",

  // Party / Nightlife
  party: "🎉",
  celebration: "🎉",
  celebrate: "🎉",
  music: "🎵",
  song: "🎵",
  singing: "🎵",
  dance: "💃",
  dancing: "💃",
  nightclub: "🕺",
  disco: "🪩",
  lights: "🎇",
  rave: "🪩",
  lit: "🔥",
  club: "🏙️",
  turnup: "🔊",
  loud: "🔊",
  vibe: "🌈",

  // Love, Symbols & Feelings
  hearts: "💕",
  broken: "💔",
  heartbroken: "💔",
  ring: "💍",
  wedding: "👰",
  proposal: "💍",
  bouquet: "💐",
  rose: "🌹",
  flowers: "🌸",
  kissmark: "💋",
  hug: "🤗",
  desire: "🔥",
  passion: "🔥",
  fire: "🔥",
  romantic: "🌹",
  night: "🌙",
  stars: "⭐",

  // Tech & Objects
  phone: "📱",
  mobile: "📱",
  smartphone: "📱",
  computer: "💻",
  laptop: "💻",
  pc: "💻",
  message: "✉️",
  dm: "📩",
  chat: "💬",
  call: "📞",
  video: "📹",
  selfie: "🤳",
  camera: "📸",
  picture: "🖼️",
  snap: "📸",

  // Nature
  tree: "🌳",
  forest: "🌳",
  sun: "☀️",
  sunny: "☀️",
  sunshine: "☀️",
  moon: "🌙",

  star: "⭐",

  flame: "🔥",
  burning: "🔥",
  water: "💧",
  rain: "💧",
  flower: "🌸",

  bloom: "🌸",
  ocean: "🌊",
  beach: "🏖️",
  sunset: "🌇",
  fuck: "YOU",
};
